### ISSUE TITLE
Lacking samples for json parser

### ISSUE THREAD

**Issue by momuno** [Azure/azure-sdk-for-c#842] opened 2020-06-16 21:04 UTC
**Is your feature request related to a problem? Please describe.**
The az_json_parser does not have quality documentation for the end-user.  The only current examples are in the test files or the provisioning service files (core/az_core/test/test_az_json.c), (iot/provisioning/src/az_iot_provisioning_client.c)

**Describe the solution you'd like**
json parser needs documented examples for end users to learn from that are easy to find/access,

**Comment by ahsonkhan** [comment] 2020-07-10 20:02
Closing as duplicate of https://github.com/Azure/azure-sdk-for-c/issues/903

**Closed by ahsonkhan** 2020-07-10 20:02 UTC
Labels: Azure.Core, Docs
