### ISSUE TITLE
doxygen comments should include code samples

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#307] opened 2020-01-15 19:01 UTC
feedback on other SDKs is that the documentation should include code snippets that will illustrate how to use the items documented.

**Comment by ahsonkhan** [comment] 2020-07-30 20:19
Other languages have sample apps which put regions around the relevant sample code snippet. We could have the doxygen generation put the snippets in the docs and this way samples compile and run.

We currently have some code snippets in the README, but having more copy-pastable samples just for core could be useful.
https://github.com/Azure/azure-sdk-for-c/blob/master/sdk/docs/core/README.md#working-with-spans

The IoT client already has extensive samples which is the mainline scenario (for example https://github.com/Azure/azure-sdk-for-c/tree/master/sdk/samples/iot/provisioning/src).

Hence moving to backlog.

**Comment by vhvb1989** [comment] 2020-08-17 21:59
@danieljurek based on Ashon comment

>The IoT client already has extensive samples which is the mainline scenario (for example https://github.com/Azure/azure-sdk-for-c/tree/master/sdk/samples/iot/provisioning/src).

Can we consider this issue done?   

It makes sense that service client are expected to be documented with examples.  Not so sure if azure core should be like that as well.

**Comment by ahsonkhan** [comment] 2020-08-17 22:09
> Not so sure if azure core should be like that as well.

We should do it for azure core as well, it is just lower priority. The issue is in the backlog. I don't think we should close it.

**Closed** 2024-03-15 18:05 UTC
Labels: Docs, Client, Azure.Core
