### ISSUE TITLE
Failed to call az_json_writer_append_string to append data with sufficient buffer

### ISSUE THREAD

**Issue by bo-ms** [Azure/azure-sdk-for-c#1107] opened 2020-08-24 16:19 UTC
json_writer buffer size is 128 bytes and the total bytes written is 52 bytes, but failed to call az_json_writer_append_string to append 20 bytes.

code: 1.0.0-preview.4

When calling az_json_writer_append_string, the json_writer buffer size is 128, total bytes written is 52 bytes, value size is 20 bytes and _az_MAX_UNESCAPED_STRING_SIZE_PER_CHUNK is 10, then call az_json_writer_append_string_chunked.
![image](https://user-images.githubusercontent.com/50469338/91068682-35fcc780-e667-11ea-82db-4bca6e399cc7.png)

In az_json_writer_append_string_chunked, after appending 20 bytes + '"' between line484-line535, the total bytes written is updated to 73 bytes and the remaining size is updated to 55 bytes, then continue to append ‘“’ (1 byte) at line 539, but there is remaining buffer size (55) check with _az_MINIMUM_STRING_CHUNK_SIZE (64) at line 537, failed (55 < 64). 
Why do we need to make sure the remaining buffer size must not be less than 64 for appending 1 byte ‘”’? could you help to check it? Thanks.
![image](https://user-images.githubusercontent.com/50469338/91068004-3779c000-e666-11ea-9a41-24cce2d5fcc9.png)

**Comment by RickWinter** [comment] 2020-08-24 16:35
@ahsonkhan Why do we require a minimum of 64 bytes to append?

> Why do we need to make sure the remaining buffer size must not be less than 64 for appending 1 byte ‘”’? could you help to check it? Thanks.

**Comment by ahsonkhan** [comment] 2020-08-24 18:19
This is by design to reduce code size and simplifying the append logic when supporting writing to discontiguous buffers. The JSON writer requires 64 bytes of slack space.

Also, appending a 20 byte character, in the worst case could be escaped and expand to 120 (if we used unicode escaping of the form \XXXX), or 40 bytes if the characters needed to be "normally" escaped with `\`. That is why `_az_MAX_UNESCAPED_STRING_SIZE_PER_CHUNK` is 10 (64/6). We could, theoretically, make that 32, but that is a bit too brittle if we change the escaping behavior in the future, to be more strict.

See related issue: https://github.com/Azure/azure-sdk-for-c/issues/1030#issuecomment-671594055

In most cases, the user is **not just** writing a single string as JSON but rather appending a sequence of tokens. Asking for extra space (that doesn't necessarily snuggly fit into the  destination) helps avoid asking for more buffer space later on, when appending smaller tokens like }, ], 123, etc.

@bo-ms - what is your actual use case which is being impacted by the json writer behavior? **Can you share a code snippet of what you are trying to achieve and how you are using the writer?**

That said, if the scenario is compelling. it is possible for us to change the behavior for a single contiguous buffer to not go down path.

**Comment by bo-ms** [comment] 2020-08-25 01:53
Hi @ahsonkhan [Here ](https://dev.azure.com/ExpressLogic/X-Ware/_git/netx?path=%2Faddons%2Fazure_iot%2Fsamples%2Fsample_azure_iot_embedded_sdk_pnp.c&version=GBboche%2Fincrease_buffer_for_json_writer-on-maintenance-rel_6.0_update&line=332&lineEnd=383&lineStartColumn=1&lineEndColumn=2&lineStyle=plain) is the code for using json to build direct method response, 

Sample scenario: 

Azure IoT Explorer sends following command to device,
![image](https://user-images.githubusercontent.com/50469338/91113063-3c1a9480-e6b7-11ea-94fd-b638dd0daf51.png)

After receiving the command, device sends response (110 bytes)
{"maxTemp":45,"minTemp":22,"avgTemp":22.5,"startTime":"2020-08-24T16:00:00Z","endTime":"2023-01-10T10:00:00Z"}

In 1.0.0-preview.3, Device can fill the 110 bytes response in 128 buffer, but failed to fill the 110 bytes response in the same buffer in 1.0.0-preview.4. We have to increase the buffer to 256. Do you think it is reasonable?
![image](https://user-images.githubusercontent.com/50469338/91113444-2e194380-e6b8-11ea-8781-e303da39c2f7.png)

**Comment by ahsonkhan** [comment] 2020-08-25 02:21
> In 1.0.0-preview.3, Device can fill the 110 bytes response in 128 buffer, but failed to fill the 110 bytes response in the same buffer in 1.0.0-preview.4. We have to increase the buffer to 256. Do you think it is reasonable?

**Yes.** You can assume that you'll need **expected JSON payload size + 64 bytes of slack** as the destination buffer size. So, in your case, 110 + 64 = 174 would be enough. If you prefer using powers of two, 256 works as well. The actual number of bytes/space used is identical though, at 110, so we are not actually writing more data.

Even though you are writing into a single contiguous destination buffer, and it might be surprising to require the extra space for that case, this behavior is identical to when you try to write the JSON split into several discontiguous buffers. Having behavioral consistency between those two scenarios is useful, imo.

**Comment by ahsonkhan** [comment] 2020-08-25 02:51
We have similar pessimistic destination size requirements when appending ints.
```C
{
// We need it to be 11 to account for the worst case, when writing a single int32 value.
uint8_t array[11] = { 0 };
az_span destination = AZ_SPAN_FROM_BUFFER(array);

az_json_writer writer = { 0 };

// A destination size of 5 is too small to hold any arbitrary integer, even though it might be
// large enough for "5" This needs to be at least 11, because we don't calculate the exact
// requried size up front, but pessimistically assume the worst case.
TEST_EXPECT_SUCCESS(az_json_writer_init(&writer, az_span_slice(destination, 0, 5), NULL));

// This is expected to fail with AZ_ERROR_INSUFFICIENT_SPAN_SIZE
assert_int_equal(az_json_writer_append_int32(&writer, 5), AZ_ERROR_INSUFFICIENT_SPAN_SIZE);

TEST_EXPECT_SUCCESS(az_json_writer_init(&writer, destination, NULL));
TEST_EXPECT_SUCCESS(az_json_writer_append_int32(&writer, 5));
az_span_to_str((char*)array, 200, az_json_writer_get_bytes_used_in_destination(&writer));
assert_string_equal(array, "5");
}
```

Given the explanation, @bo-ms, please let me know if this behavior is a blocker for you or if the workaround to add some slack is good enough. If this is a concern, I will re-evaluate the design trade-offs.

**Comment by bo-ms** [comment] 2020-08-25 03:19
@ahsonkhan we can increase the buffer size for now, it is not a locker for me, just want to bring it up to you.

**Comment by ahsonkhan** [comment] 2020-09-08 22:01
Closing this as by design/fixed. I will follow up offline if we still want to change the implementation/design.

**Closed by ahsonkhan** 2020-09-08 22:01 UTC
Labels: Azure.Core, Client, customer-reported, question
