### ISSUE TITLE
Output map files from build

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-c#241] opened 2019-12-02 18:10 UTC
Get map files from each build to begin investigating binary size

**Comment by danieljurek** [comment] 2020-04-20 18:37
Also: https://interrupt.memfault.com/blog/code-size-deltas

**Comment by danieljurek** [comment] 2020-07-20 17:54
From discussion last week 

* The size of the map file itself is not a strong indicator of the binary size
* Map files need an executable (e.g. a sample) to be produced because there needs to be enough information for linking to take place. In that case you'll see a map file per build. 
  * The IoT team is especially interested in binary size attributable to the SDK for samples that use the JSON parser
* Map file formats vary based on the build tools being used
* Some build tools like IAR output an easy to read summary at the end of the map file

**Comment by ahsonkhan** [comment] 2020-07-30 20:14
Duplicate of https://github.com/Azure/azure-sdk-for-c/issues/240

**Closed by ahsonkhan** 2020-07-30 20:14 UTC
Labels: EngSys
