### ISSUE TITLE
Let's define code coverage minimums and enforce them.

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-c#417] opened 2020-03-03 22:00 UTC
For the beginning, we can go with the current 79.7% for lines, 73.5% for functions, focus on never reducing that number, then increase them soon, and stick to that updated baseline. 85% sounds like a reasonable minimum, a number that is >= 90% sounds like the good one. Ideally, we should cover as much as we could while not covering only the places we can't cover due to technical reasons, reasonably.

**Comment by gilbertw** [comment] 2020-03-03 22:05
This is a duplicate of the bug assigned to Daniel #411

**Closed by gilbertw** 2020-03-03 22:05 UTC
